### ISSUE TITLE
ALS: experimental XAS/XMCD data

### ISSUE THREAD

**Issue by tschaume** [materialsproject/MPContribsUsers#3]
In collaboration with @ATNDiaye, a workflow is developed for the contribution of XAS/XMCD spectra measured at the ALS. Subsequent analysis enables the comparison of the data to theoretical phase diagrams provided by MP. In the future, the researcher could compare his or her contributed XAS data to FEFF calculations to get a better handle on the composition of the sample.

The pre-processing phase uses a bare-bone `MPFile` as input. It contains the lab-book meta-data as well as processing instructions to configure and control the generation of the tabular XAS/XMCD data from instrumental output. See, `python -m mpcontribsusers.atn test_files/atn_data`.

This use-case is featured in our recent [paper](https://github.com/tschaume/mp-docs/blob/c4264ba/GCE15/gce15.pdf) titled "User Applications Driven by the Community Contribution Framework MPContribs in the Materials Project" submitted to the 10th Gateway Computing Environments Workshop ([GCE15](http://sciencegateways.org/upcoming-events/gce15/)).

List of ToDo's:
- [x] improve `MPFile` I/O capabilities:
  - [x] `get_string`: materialsproject/MPContribs@244f4468a564ad6d620ceaa7f9021ba8854911b7, materialsproject/MPContribs@f6cdf14ababd3dcd618268f6a6cb4e091165e9ce
  - [x] `add_data_table`: materialsproject/MPContribs@fd0dfc7f0a29c3cede431ec9d55651a017147f4f
  - [x] `get_identifiers`: materialsproject/MPContribs@62761e15a8008c950f086e94921de259dbbdb667
- [x] develop alpha-version of pre-processing workflow, see merged pull request #1 
- [x] develop rudimentary `MPFile` viewer, see materialsproject/MPContribs#8
- [x] migrate to separate database, see materialsproject/MPContribs#4
- [x] update builder phase to cope with composition-based contributions, included in materialsproject/MPContribs#4
- [x] discuss collaboration on demo scenario for [Science Gateway](sciencegateways.org/upcoming-events/gce15/) paper
- [x] improve book-keeping, see materialsproject/MPContribs#3
- [x] organize directory of instrumental output files for realistic end-to-end demo @ATNDiaye 
- [x] initiate new pull request with possible code updates to cover full example, see #6 @ATNDiaye 
- [x] deploy _Composition Detail Pages_ to collect composition-based contributions, see materialsproject/materials_django#426
- [x] submit Science Gateway [paper](https://github.com/tschaume/mp-docs/blob/c4264ba/GCE15/gce15.pdf) to conference
- [x] start work on post-analysis of contributed test data:
  - [x] grab spectra and phase diagram from MP and compile PDF
  - [x] mark contributed compositions in MP phase diagram
  - [x] heatmap of magnetic moment vs composition, close #6
- [x] make `MPFileViewer` work offline for speed and data protection, see materialsproject/MPContribs#13
- [x] `MPFileViewer`: graphs-only view of `MPFile` contents, see materialsproject/MPContribs#15
- [ ] release framework for beta-testers (LBNL internal only?)

**Comment by tschaume** [comment]
FYI @ATNDiaye and @kristinpersson, a brief summary of the current status of the ALS workflow. 

[This MPFile](https://github.com/materialsproject/MPContribs/blob/701336a/test_files/atn_Ni20Fe80_mult.txt) is generated from instrumental and lab-book data via the [pre-submission scripts](https://github.com/materialsproject/MPContribsUsers/tree/master/mpcontribsusers/atn) in  `mpcontribsusers.atn` (see pull requests #1 and #6). Its submission to MP via the `MPContribs` framework results in the presentation of the `Ni20Fe80Pt1` contribution data, for instance, at
https://materialsproject.org/compositions/Ni20Fe80Pt1/contributions#LBNL#0377c81:
![composition ni20fe80pt1](https://cloud.githubusercontent.com/assets/1404564/8915459/fa304980-3459-11e5-9970-4166b2e9cc52.png)

The [post-submission script](https://github.com/materialsproject/MPContribsUsers/blob/master/mpcontribsusers/atn/post_submission.py) (also part of `mpcontribsusers.atn`) integrates the experimental ALS results with MP's theoretical phase diagrams (PD). It pulls the contributed XAS spectra from MP's database, generates the PD for the Ni-Fe-Pt chemical system, embeds points into the PD where the contributed data would lie, and generates a PDF compiling the results:
![test-nup](https://cloud.githubusercontent.com/assets/1404564/8915498/34f98914-345a-11e5-93e4-8e1d12731b7a.png)
If desired, it'd be straight-forward to convert the post-submission script into a small ALS-specific web app. This would be proof of concept how user's could design simple web apps based on MP's infrastructure (@kristinpersson: think NREL's photovoltaic app) while simultaneously contributing their data to a (well-maintained) community database.

To devise a first version of the full end-to-end ALS workflow, magnetic moments need to be calculated from the spectra and included in the PD in form of a heatmap replacing the red points in the above screenshot. @ATNDiaye and @tschaume will follow up offline.

**Comment by tschaume** [comment]
closed in favor of #34
