### ISSUE TITLE
RedoxThermoCSP

### ISSUE THREAD

**Issue by tschaume** [materialsproject/MPContribsUsers#51]
- [x] submit theoretical structures for calculation  josuav1/solar_perovskite#5
- [x] build in Josua's graph updates (parent of #55)
- [x] match structures to mp-id's
- [x] add Ellingham graph #61 
- [x] make sure all materials appear on MP dev (used in solar_perovskites code)
- [x] add second trace to Ellingham graph
- [x] update solar_perovskites to fix wrong reaction paths  
josuav1/solar_perovskite@466437d
- [x] merge v3 #65 
- [x] remove shomate parameters from DB
- [x] Fix the images in the documentation
- In the table:
  * [x] Remove oxidized phase: crystal structure
  * [x] Add “data availability”: “Both” or “Theo”
  * [x] Add pars[‘theo_compstr’] from the contributions
  * [x] fix theo_compstr typo for `Ca08.75Sr0.125Mn0.75Fe0.25Ox`
- [x] access for group only, sync DLR accounts to alpha
- [x] make sure `requires_api_key=True` in `rest.views`
---

- [x] Move data from json files into the contribution database
- [x] Add theoretical data using the little json file I sent you
- [x] use comp_str for theo isographs (not act_mat)
- [ ] overlay 4 experimental iso* with according theoretical curves
- [ ] add 2 plots for dH/dS - each with isobar, isotherm, exp data, and fit
- [x] add SNLs for `redox_thermo_csp` calculations
- [x] queue up calculated materials for elastic tensor calculations
- [ ] highlight selected row on click
- [x] update graphs on slider adjustment
- [ ] add water and CO2 splitting line to ellingham
- [x] energy analysis

**Comment by josuav1** [comment]
@tschaume We need to change the name of the project in the production page, if that is still possible. The name currently still says "dlr_vieten", but I'll put the URLs https://contribs.materialsproject.org/redox_thermo_csp 
and https://github.com/materialsproject/MPContribsUsers/tree/master/redox_thermo_csp
in the paper.

**Comment by tschaume** [comment]
fixed via 26fbe78

Please use https://materialsproject.org/mpcontribs/redox_thermo_csp to link to the landing page (will go live with next production release)
